### ISSUE TITLE
README mistake

### ISSUE THREAD

**Issue by Ivansstyle** [jmacey/GitActionExample#1]
Hi Jon! 
By  ".github/workspace" in README.md you probably meant ".github/workflows".

**Comment by jmacey** [comment]
good spot, I will update :-) Hope your well. I intend to write more on this soon once I have got some more stuff sorted.

**Comment by Ivansstyle** [comment]
Hi, doing well! Hope you are well too. Yes, very useful and modern for CI/CD and testing. Will be watching!
